# Generated by Django 5.1.6 on 2025-02-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='refresh_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
