# Generated by Django 5.1.6 on 2025-03-01 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_userauth_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auths', to=settings.AUTH_USER_MODEL),
        ),
    ]
