# Generated by Django 5.1.6 on 2025-03-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_rename_user_qr_user_id_rename_user_table_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
