# Generated by Django 5.1.6 on 2025-03-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_table_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='image',
            field=models.CharField(),
        ),
    ]
